version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  hazelcast:
    image: hazelcast/hazelcast:4.0
    ports:
      - "5701:5701"
    volumes:
      - hazelcast_data:/data/hazelcast

  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - elasticsearch
      - hazelcast

volumes:
  mongodb_data:
  elasticsearch_data:
  hazelcast_data:
